nohup python edm_train.py \
    --attention_resolutions 32,16,8 \
    --class_cond False \
    --use_scale_shift_norm True \
    --dropout 0.0 \
    --ema_rate 0.9999 \
    --global_batch_size 4096 \
    --batch_size 48 \
    --image_size 64 \
    --lr 0.0001 \
    --num_channels 192 \
    --num_head_channels 64 \
    --num_res_blocks 3 \
    --resblock_updown True \
    --schedule_sampler lognormal \
    --use_fp16 True \
    --weight_decay 0.0 \
    --weight_schedule karras \
    --data_dir /home/bratosiewicz/data/ffhq/train \
    --log_interval 100 \
    --log_dir /home/bratosiewicz/consistency_models/out/10-12-ffhq \
    > 10-12_training.log 2>&1 &